version: '3'
services:
  dns-txt-proxy:
#    #动手能力强的，手动通过Dockerfile构建镜像
#    build:
#      context: .
#      dockerfile: Dockerfile
    #或用其他方式构建后的现在镜像
    image: nary24/dns-txt-proxy:latest
    container_name: dns-txt-proxy
    restart: always
    volumes:
      - $PWD/config.conf:/app/config.conf      #修改$PWD/config.conf路径为你的实例配置文件路径 比如：/home/dns-txt-proxy/config.conf
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"

# windows上的host模式网络不通，使用以下端口映射，根据情况手动配置
#    ports:
#      - 8888:8888/udp
#      - 5000:5000